name: Test Automation Work Flow

on:
  schedule:
    - cron: '01 17 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running test Automation Framework with Maven
        run: mvn test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test logs
          path: logs/

      - name: Upload Screenshot as Artifacts
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: screenshots
          path: screenshots/
          
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test Reports
          path: report.html
          
      - name: Test Execution Status
        if: always()
        run: echo "Test execution completed"      

      - name: Copy Report to gh-pages Folder
        if: always()
        run: |
          mkdir -p public/extent-reports
          cp -R report.html public/extent-reports/
          # Only copy screenshots if the folder exists
          if [ -d "screenshots" ]; then
            cp -R screenshots/ public/extent-reports/screenshots/
          fi
          ls -l public/extent-reports
          
      - name: Deploy
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public/extent-reports/
          token: ${{ secrets.PAT12345 }}
          clean: true
          branch: gh-pages
          force: true
      
          
