name: Test Automation Work Flow

on:
  schedule:
    - cron: '01 17 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Running test Automation Framework with Maven
        run: mvn test -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test Reports
          path: report.html

      - name: Test Execution Status
        run: echo "Test execution completed"
